server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/v1/bookings/**
            - Method=GET,POST,DELETE
          filters:
            - name: Retry
              args:
                retries: 3
                methods: POST, GET, DELETE
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 2s
            - name: CircuitBreaker
              args:
                name: bookingService
                fallbackUri: forward:/fallback/bookings

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

