server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
          filters:
            -name: CircuitBreaker
            args:
              name: booking-service
              fallbackUrl: forward:/booking-fallback

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            -name: CircuitBreaker
            args:
              name: payment-service
              fallbackUrl: forward:/payment-fallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
